# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'
User.delete_all
ArtPiece.delete_all

u1 = User.create(full_name: 'Randy Strong', email: '123@bam.com', password: 'password', is_client: false, img_url: "http://www.rstrong.com/wp-content/uploads/2012/05/randy_strong.jpg", bio: "Winner of the juried 2005 and 2008 Niche award for blown glass and finalist for 2010 – awarded by Niche magazine for the best of blown glass in the United States – Randy Strong – artist and designer in hot glass for 40 years, has worked continuously throughout his career producing innovative designs in glass that continually influence the ever changing and growing community of studio glass artists. Randy’s work through the last 4 decades has been characterized by the use of difficult, defining techniques, materials, colors and forms. His newest sculptural work again breaks new ground by challenging the concept of solid form in glass by further expressing its personality in lightness and movement.", lat: 38.373095, lng: -122.796544, address: "1235 4th St, Berkeley, CA 94710")
u2 = User.create(full_name: 'Bryan Goldenberg',email: '456@bam.com', password: 'password', is_client: false, bio: 'Originally from St. Louis, I moved to Oakland, CA and earned a BFA in glass concentration from California College of Arts & Crafts in 2002. During the course of my training, I toured the world exploring studios from Inferno Glass Studio in New Orleans, to Pilchuck Glass School in Seattle, to studios in Murano, Italy. It has been my honor to blow glass with widely renowned glass artists such as Dante Marioni, Lino Tagliapietra, Hank Adams, and Clifford Rainey.

Currently my work can be seen in premier glass art galleries and museums across America. I was the featured artist at a solo-show at the Wynn Hotel, Las Vegas, Nevada in June 2007, and returned again for a solo shows in October 2008 & 2010. As an active member of the American Craft Council, and with multiple features publications and media shows, I have been called “One of the most up and coming contemporary artists of our time”.', img_url: "https://www.slowburnglass.com/wp-content/uploads/2019/01/bryan.jpg", lat: 37.9204296, lng: -122.3521971, address: "833 S 19th St. Unit A
Richmond, CA 94804")
u3 = User.create(full_name: 'Zak Timan',email: '789@bam.com', password: 'password', is_client: false, bio: "Zak Timan is based out of San Francisco, California and received his education at California College of the Arts. He has been featured in several exhibits such as Museum of Art And Design, New York, Bedford Gallery, Walnut Creek, CA, CENART, Mexico City, Mexico, Palazzo Cavalli Franchetti, Venice, Italy, and the American International Fine Art Fair - Palm Beach, FL. He currently holds a residency at Tacoma Museum of Glass.", img_url: "https://s3-media0.fl.yelpcdn.com/bphoto/yO8QeiNvNDNFbis3IxMPoQ/o.jpg", lat: 37.9130451, lng: -122.327782, address: "1345 S 50th St, Richmond, CA 94804")
p1 = ArtPiece.create(name: "Glass Crab Figurine", img_url: "https://i.etsystatic.com/9842326/d/il/190186/2420194096/il_340x270.2420194096_hfnl.jpg?version=0", creator_name: u1.full_name, description: "Crab is another fascinating sea creature that has significant symbolical and spiritual importance to humans. This strange looking animal has been inspiration to people since ancient times to modern day.", owned: false)
p2 = ArtPiece.create(name: "Molten Glass Bowl", img_url: "https://i.etsystatic.com/19309300/d/il/1ab4b4/2666797202/il_340x270.2666797202_opuv.jpg?version=0", creator_name: u3.full_name, description: "This Molten Glass Bowl Is A Functional Item. The Glass Is Removable And Can Be Used To Hold A Myriad Of Items From Candy To Pebbles To Small Fish!", owned: false)
p3 = ArtPiece.create(name: "Wave", img_url: "https://i.etsystatic.com/7682946/d/il/b25e86/1876206298/il_340x270.1876206298_6mfy.jpg?version=0", creator_name: u2.full_name, description: "Wave is 4 1/2 inches tall by 6 inches wide, maybe slightly smaller. This wave can curl over further without blocking the waves face, and gives a more tubular profile view.", owned: false)
p4 = ArtPiece.create(name: "Glass Universe Pendant", img_url: "https://i.etsystatic.com/16223047/d/il/cda36f/1957281616/il_340x270.1957281616_1r8c.jpg?version=0", creator_name: u2.full_name, description: "This universe glass pendant has a fabulous three-dimensional interior design and takes on various aesthetic looks in different lighting conditions.", owned: false)
p5 = ArtPiece.create(name: "Blueberry", img_url: "https://i.etsystatic.com/5624505/d/il/dd76a4/2375329807/il_340x270.2375329807_68t8.jpg?version=0", creator_name: u3.full_name, description: "Glass Ripe Blueberry, realistic and life-sized handblown glass figurine, good enough to fool the eye. They are miniature heirloom-quality art works. A treasured collectible for any gourmet, gardener or blueberry lover.", owned: false)
p6 = ArtPiece.create(name: "Red Spider Figurine", img_url: "https://i.etsystatic.com/23495591/c/2475/1967/179/63/il/b78a46/2801441548/il_340x270.2801441548_f1kt.jpg", creator_name: u1.full_name, description: "Beautiful model of a handmade Art glass Red Spider figurine made of blown glass using the lampwork technique.", owned: false)
p7 = ArtPiece.create(name: "Blue Flowers", img_url: "https://i.etsystatic.com/14244445/c/853/677/0/69/il/04ee74/2684916526/il_340x270.2684916526_te5i.jpg", creator_name: u2.full_name, description: "FUSED Blown Glass Design, combines an ancient blown glass technique with hand paint color resins to create magnificent colorful blown glass designs.", owned: false)
p8 = ArtPiece.create(name: "Prince Frog", img_url: "https://i.etsystatic.com/9842326/r/il/109343/2325433250/il_794xN.2325433250_fc3z.jpg", creator_name: u1.full_name, description: "The frog totem symbolizes the cycles of life, in particular, the rebirth stage. Its own journey through life, from tadpole to the adult state, reminds us of the many cycles of transformation and rebirth in our lives.", owned: false)
p9 = ArtPiece.create(name: "Anchor Figurine", img_url: "https://i.etsystatic.com/6329281/d/il/2be886/2207989932/il_340x270.2207989932_8f53.jpg?version=0", creator_name: u3.full_name, description: "Resting among the rocky shoals represented by genuine amethyst crystals, this anchor lies with its rusty old chain coiled around it. Maritime collectors will love it.", owned: false)
p10 = ArtPiece.create(name: "Black Octopus", img_url: "https://i.etsystatic.com/6192228/d/il/2bb2c3/2305014061/il_340x270.2305014061_r35z.jpg?version=0", creator_name: u1.full_name, description: "These octopus make a wonderful addition for any octopus enthusiast. They come in black, red, green, blue, or teal.", owned: false)
p11 = ArtPiece.create(name: "Orange Figurine", img_url: "https://i.etsystatic.com/24179794/d/il/385094/2784412385/il_340x270.2784412385_rp46.jpg?version=0", creator_name: u2.full_name, description: "Our Murano glass fruit is handmade, blown glass from the island of Murano. We add Millefiori mosaics to the objects along with 18k gold foil for a beautifully regal finished product.", owned: false)
p12 = ArtPiece.create(name: "Ruby Dichroic Glass Heart", img_url: "https://i.etsystatic.com/6738226/d/il/b3f8a1/2874039571/il_340x270.2874039571_qh91.jpg?version=1", creator_name: u3.full_name, description: "One Cast heart paperweight with shimmering pieces of dichroic glass. Dichroic glass patterns will vary and dichroic glass glimmers differently depending on lighting.", owned: false)
p13 = ArtPiece.create(name: "Llama Figurine", img_url: "https://i.etsystatic.com/6329281/d/il/a7c63f/2223707180/il_340x270.2223707180_m87e.jpg?version=0", creator_name: u1.full_name, description: "Llama Figurine of Hand Blown Glass and 24K Gold. It is no wonder why folks are attracted to this unusual animal with its large doe eyes, long rabbit ears, toes on each foot, giraffe like neck, and fur that is used in fine woolens.", owned: false)
p14 = ArtPiece.create(name: "Pendant Lighting", img_url: "https://i.etsystatic.com/7539039/d/il/81e913/2615790098/il_340x270.2615790098_iges.jpg?version=0", creator_name: u2.full_name, description: "Vintage White Glass - Mid century modern - pendant lighting - hand blown glass - ceiling fixture - brass light - made in the USA", owned: false)
p15 = ArtPiece.create(name: "Art Bowl", img_url: "https://i.etsystatic.com/5725003/d/il/7a9ca7/2700204566/il_340x270.2700204566_6kmo.jpg?version=0", creator_name: u3.full_name, description: 'Beautiful Hand Blown Glass Art bowl measures approximately 18" across the widest part of the bowl and 6" deep.', owned: false)
p16 = ArtPiece.create(name: "Grizzy Figurine", img_url: "https://i.etsystatic.com/6329281/d/il/0d8604/245059858/il_340x270.245059858.jpg?version=0", creator_name: u1.full_name, description: "Possessing all the characteristics of an inquisitive grizzly is this expressive hand crafted bear sculpture. I make the figurine entirely by hand of borosilicate crystal.", owned: false)
p17 = ArtPiece.create(name: "Blown Mezcal Bottle", img_url: "https://i.etsystatic.com/23962255/d/il/0b997d/2700502091/il_340x270.2700502091_jz6q.jpg?version=0", creator_name: u2.full_name, description: "This is an amazing hand-blown wasp catcher mezcal bottle. A true art piece made to impress at any occasion! Made by our master blowers in Mexico.", owned: false)
p18 = ArtPiece.create(name: "Ceiling Hung Crystal Ball", img_url: "https://i.etsystatic.com/24534951/r/il/2b86e6/2822970549/il_794xN.2822970549_7y9o.jpg", creator_name: u3.full_name, description: "Willis at River Lighting components are made in America - most of them by multi-generation family businesses, some of which have been around for over 100 years! Their quality is unparalleled, and we're proud to be a part of this rich community of home-grown entrepreneurs and artisans.", owned: false)


